spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/task_management
    username: postgres
    password: postgres
    hikari:
      schema: user_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS user_schema
      connection-timeout: 10000
  jpa:
    generate-ddl: true

app:
  jwt:
    secret: "someSecretKey"
    tokenExpiration: 60m


